import { IReleases, IReleasesCard } from '../../redux/Releases/types';

export const ReleasesList: IReleases[] = [
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.45',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '02.50',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.30',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '04.00',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '04.15',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.25',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-3.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.55',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-3.png'),
        iconImg: require('./img/like.png'),
    },
];

export const CardList: IReleasesCard[] = [
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Soulful Insurrection',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-1.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Lyric Renaissance',
        time: '03.44',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Drumbeat Revolution',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-3.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Resonance Revival',
        time: '03.15',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-4.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Bassline Uprising',
        time: '03.25',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-5.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Lyric Renaissance',
        time: '03.30',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-6.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Melody Vanguard',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-7.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Rhyme Revolution',
        time: '03.35',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-8.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Soulful Insurrection',
        time: '03.45',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-9.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Lyric Renaissance',
        time: '03.55',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-10.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Drumbeat Revolution',
        time: '03.30',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-11.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Resonance Revival',
        time: '03.27',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-12.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Bassline Uprising',
        time: '03.18',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-13.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Lyric Renaissance',
        time: '03.10',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-14.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Melody Vanguard',
        time: '03.00',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-15.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Rhyme Revolution',
        time: '03.05',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-16.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Bassline Uprising',
        time: '03.12',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-17.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        name: 'Melody Vanguard',
        time: '03.18',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-18.png'),
        iconImg: require('./img/like.png'),
    },
];
