import { IReleases } from '../../redux/Releases/types';

export const ReleasesGroups: IReleases[] = [
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.45',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '02.50',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.30',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '04.00',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '04.15',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.25',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-3.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.55',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-3.png'),
        iconImg: require('./img/like.png'),
    },
];

export const ReleasesList = [
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.45',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '02.50',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.30',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '04.00',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '04.15',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.25',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-3.png'),
        iconImg: require('./img/like.png'),
    },
    {
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.55',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-3.png'),
        iconImg: require('./img/like.png'),
    },
];
