import { IReleasesCard } from '../../redux/Releases/types';

export const releasesList: IReleasesCard[] = [
    {
        id: '11',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful.png'),
    },
    {
        id: '22',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.45',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-2.png'),
    },
    {
        id: '33',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '02.50',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat.png'),
    },
    {
        id: '44',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.30',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline.png'),
    },
    {
        id: '55',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '04.00',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat-2.png'),
    },
    {
        id: '66',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '04.15',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-2.png'),
    },
    {
        id: '77',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.25',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-3.png'),
    },
    {
        id: '88',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.55',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-3.png'),
    },
];

export const сardList: IReleasesCard[] = [
    {
        id: '1',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-1.png'),
    },
    {
        id: '2',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Lyric Renaissance',
        time: '03.44',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-2.png'),
    },
    {
        id: '3',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-3.png'),
    },
    {
        id: '4',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Resonance Revival',
        time: '03.15',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-4.png'),
    },
    {
        id: '5',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.25',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-5.png'),
    },
    {
        id: '6',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Lyric Renaissance',
        time: '03.30',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-6.png'),
    },
    {
        id: '7',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Melody Vanguard',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-7.png'),
    },
    {
        id: '8',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Rhyme Revolution',
        time: '03.35',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-8.png'),
    },
    {
        id: '9',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.45',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-9.png'),
    },
    {
        id: '10',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Lyric Renaissance',
        time: '03.55',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-10.png'),
    },
    {
        id: '11',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '03.30',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-11.png'),
    },
    {
        id: '12',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Resonance Revival',
        time: '03.27',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-12.png'),
    },
    {
        id: '13',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.18',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-13.png'),
    },
    {
        id: '14',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Lyric Renaissance',
        time: '03.10',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-14.png'),
    },
    {
        id: '15',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Melody Vanguard',
        time: '03.00',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-15.png'),
    },
    {
        id: '16',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Rhyme Revolution',
        time: '03.05',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-16.png'),
    },
    {
        id: '7',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.12',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-17.png'),
    },
    {
        id: '18',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Melody Vanguard',
        time: '03.18',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/s-18.png'),
    },
];
