import { IReleases } from '../../redux/Releases/types';

export const releasesList: IReleases[] = [
    {
        id: '1',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.20',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful.png'),
        iconImg: require('./img/like.png'),
    },
    {
        id: '2',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.45',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        id: '3',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '02.50',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat.png'),
        iconImg: require('./img/like.png'),
    },
    {
        id: '4',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.30',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline.png'),
        iconImg: require('./img/like.png'),
    },
    {
        id: '5',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Drumbeat Revolution',
        time: '04.00',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/drumbeat-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        id: '6',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '04.15',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-2.png'),
        iconImg: require('./img/like.png'),
    },
    {
        id: '7',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Soulful Insurrection',
        time: '03.25',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/soulful-3.png'),
        iconImg: require('./img/like.png'),
    },
    {
        id: '8',
        url: 'https://demo.templatemonster.com/ru/demo/349984.html',
        title: 'Bassline Uprising',
        time: '03.55',
        author: 'Elysia Rayne, Jaxon Grey',
        imgUrl: require('./img/bassline-3.png'),
        iconImg: require('./img/like.png'),
    },
];
