import { IPlaylistSong } from '../../redux/Playlist/types';

export const PlaylistSong: IPlaylistSong[] = [
    {
        title: 'Harmonic Riot 1',
        author: 'Jennifer Kelly 1',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 2',
        author: 'Jennifer Kelly 2',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 3',
        author: 'Jennifer Kelly 3',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 4',
        author: 'Jennifer Kelly 4',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 5',
        author: 'Jennifer Kelly 5',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 6',
        author: 'Jennifer Kelly 6',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 7',
        author: 'Jennifer Kelly 7',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 8',
        author: 'Jennifer Kelly 8',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 9',
        author: 'Jennifer Kelly 9',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 10',
        author: 'Jennifer Kelly 10',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 11',
        author: 'Jennifer Kelly 11',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 12',
        author: 'Jennifer Kelly 12',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 13',
        author: 'Jennifer Kelly 13',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 14',
        author: 'Jennifer Kelly 14',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
    {
        title: 'Harmonic Riot 15',
        author: 'Jennifer Kelly 15',
        imgUrl: require('./img/song.png'),
        time: '03.20',
        iconPlay: require('./img/play.png'),
        iconLike: require('./img/like.png'),
    },
];
